import { Card } from "src/app/interfaces/card.interface";

export const MERCURIO_CARDS: Card[] =[
  {
    "id": "1772148877429",
    "name": "Sello Mercurio",
    "faction": "mercurio",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875092/mercurio-rog/sello_de_mercurio_dxawcp.png",
    "factionCost": 0,
    "cost": 0,
    "banned": false,
    "isSeal": true,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": []
  },
  {
    "id": "1772148944742",
    "name": "Núcleo bomba",
    "faction": "mercurio",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875090/mercurio-rog/nucleo_bomba_ey6hvl.jpg",
    "factionCost": 0,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Carta",
      "Daño",
      "inflinjo",
      "Robar"
    ]
  },
  {
    "id": "1772149030040",
    "name": "Mecha-tuerca",
    "faction": "mercurio",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875088/mercurio-rog/mecha_tuerca_igaifp.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Barrera"
    ]
  },
  {
    "id": "1772149079022",
    "name": "Recolector de basura",
    "faction": "mercurio",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875091/mercurio-rog/recolector_de_basura_e4ozxk.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Carta",
      "Robar",
      "Último suspiro"
    ]
  },
  {
    "id": "1772149140996",
    "name": "Cañón de protones",
    "faction": "mercurio",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875094/mercurio-rog/canon_de_protones_qcvta7.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Daño",
      "inflinjo",
      "Mazo",
      "Nucleo Bomba"
    ]
  },
  {
    "id": "1772149196972",
    "name": "Halcón de caza",
    "faction": "mercurio",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875088/mercurio-rog/halcon_de_caza_k10lyp.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1772149258126",
    "name": "Mecha replicante",
    "faction": "mercurio",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875090/mercurio-rog/mecha_replicante_r9nwig.png",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Busco",
      "Mano",
      "Mazo",
      "Último suspiro"
    ]
  },
  {
    "id": "1772149329332",
    "name": "Mecha Velobot",
    "faction": "mercurio",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875088/mercurio-rog/mecha_velobot_cts1l1.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "aliada",
      "Asalto",
      "Carta",
      "Criatura",
      "invocar",
      "Revelar",
      "Robar",
      "Sacrificar",
      "Sello"
    ]
  },
  {
    "id": "1772149396168",
    "name": "Minidrón explosivo",
    "faction": "mercurio",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875090/mercurio-rog/minidron_explosivo_acljvx.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Daño",
      "inflinjo",
      "Mezclo",
      "Nucleo Bomba",
      "Último suspiro"
    ]
  },
  {
    "id": "1772149495926",
    "name": "Tanque hidrante",
    "faction": "mercurio",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875092/mercurio-rog/tanque_hidrante_jrnkeg.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Aturdir",
      "Carta",
      "Robar"
    ]
  },
  {
    "id": "1772149581612",
    "name": "Cenizo, Ráfaga Aérea",
    "faction": "mercurio",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875088/mercurio-rog/cenizo_axzhko.png",
    "factionCost": 3,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Carta",
      "Cementerio",
      "Daño",
      "Enemiga",
      "inflinjo"
    ]
  },
  {
    "id": "1772149628156",
    "name": "Explorabot 101",
    "faction": "mercurio",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875089/mercurio-rog/explorabot_101_rlbzew.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Barrera",
      "Carta",
      "Robar"
    ]
  },
  {
    "id": "1772149702256",
    "name": "Bot Blank",
    "faction": "mercurio",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875093/mercurio-rog/bot_blank_rngsc6.png",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Daño",
      "invocar",
      "inflinjo",
      "Sacrificar",
      "Selecciona"
    ]
  },
  {
    "id": "1772228456844",
    "name": "Elegido de Mercurio",
    "faction": "mercurio",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875088/mercurio-rog/elegido_de_mercurio_bivwls.png",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Al atacar",
      "Carta",
      "Mazo",
      "Rayo Laser",
      "Robar"
    ]
  },
  {
    "id": "1772228533607",
    "name": "La Arquitecta",
    "faction": "mercurio",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875089/mercurio-rog/la_arquitecta_gv4gow.png",
    "factionCost": 4,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Barrera",
      "Carta",
      "Mazo",
      "Mezclo",
      "Nucleo Bomba",
      "otorgo",
      "Selecciona"
    ]
  },
  {
    "id": "1772228585335",
    "name": "Montacargas de Tungsteno",
    "faction": "mercurio",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875091/mercurio-rog/montacargas_de_tungsteno_t0fh2o.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Barrera",
      "Provocar"
    ]
  },
  {
    "id": "1772228638269",
    "name": "Syet, El Pistolero",
    "faction": "mercurio",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875092/mercurio-rog/syet_el_pistolero_maksny.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Destruyo"
    ]
  },
  {
    "id": "1772228715475",
    "name": "Tecnología Pilogi",
    "faction": "mercurio",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875092/mercurio-rog/tecnologia_pilogi_bikkkk.png",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Campo",
      "Criatura",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1772228761575",
    "name": "Balam Cernos",
    "faction": "mercurio",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875092/mercurio-rog/balaam_cernos_jgkcse.png",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Criatura",
      "Daño",
      "inflinjo",
      "Último suspiro"
    ]
  },
  {
    "id": "1772228811715",
    "name": "Lanzador Acorazado",
    "faction": "mercurio",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875089/mercurio-rog/lanzador_acorazado_py9zzb.png",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Criatura",
      "Daño",
      "inflinjo",
      "Mezclo",
      "Nucleo Bomba"
    ]
  },
  {
    "id": "1772228880711",
    "name": "Sentinel Vortex",
    "faction": "mercurio",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875091/mercurio-rog/sentinel_vortex_y6ykp4.jpg",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Al golpear",
      "Barrera",
      "Criatura",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1772228931066",
    "name": "Blastcore",
    "faction": "mercurio",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875093/mercurio-rog/blastcore_yerwbd.png",
    "factionCost": 3,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Mazo",
      "Mezclo",
      "Nucleo Bomba"
    ]
  },
  {
    "id": "1772229002567",
    "name": "Unidad de choque B612",
    "faction": "mercurio",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875092/mercurio-rog/unidad_de_choque_b612_kdnt6x.png",
    "factionCost": 4,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Barrera",
      "Criatura",
      "Daño"
    ]
  },
  {
    "id": "1772229094925",
    "name": "Horizonte Alfa 01",
    "faction": "mercurio",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875088/mercurio-rog/horizonte_alfa_01_bscukh.png",
    "factionCost": 4,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Al golpear",
      "Asalto",
      "Barrera",
      "Cargar",
      "Criatura",
      "curar",
      "Destruyo",
      "invocar",
      "Vida"
    ]
  },
  {
    "id": "1772229162479",
    "name": "Horizonte Omega 01",
    "faction": "mercurio",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1771875090/mercurio-rog/horizonte_omega_01_kwzk58.png",
    "factionCost": 4,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Al golpear",
      "Barrera",
      "Cargar",
      "Criatura",
      "curar",
      "Destruyo",
      "Vida"
    ]
  }
];
