import { Card } from "src/app/interfaces/card.interface";

export const NEPTUNO_CARDS: Card[] =[
  {
    "id": "1766788300726",
    "name": "Sello Neptuno",
    "faction": "neptuno",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422314/neptuno-rog/Sello-Neptuno-733x1024_fpamr9.webp",
    "factionCost": 0,
    "cost": 0,
    "banned": false,
    "isSeal": true,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": []
  },
  {
    "id": "1766788337130",
    "name": "Errante Profundo",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422303/neptuno-rog/CRIATURA-1-Errante-Profundo-733x1024_fqzhsp.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Toque mortal"
    ]
  },
  {
    "id": "1766788379146",
    "name": "Arrecife móvil",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422303/neptuno-rog/CRIATURA-2-Arrecife-Movil-733x1024_zdoy2t.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1766788448290",
    "name": "Orador de Midas",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422304/neptuno-rog/CRIATURA-2-Orador-de-Midas-733x1024_sampvi.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Creo",
      "Cofre Codicia"
    ]
  },
  {
    "id": "1766788483837",
    "name": "Arrecidaña",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422304/neptuno-rog/CRIATURA-3-Arrecidana-733x1024_zqoshq.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adelante",
      "Asalto",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1766788543414",
    "name": "Monarca astral",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422305/neptuno-rog/CRIATURA-3-Monarca-Astral-733x1024_hvkm59.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Creo",
      "Cofre Codicia",
      "Cofre pesado",
      "Mano",
      "Oponente",
      "Revelar"
    ]
  },
  {
    "id": "1766788618354",
    "name": "Retoño d Cthulu",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422305/neptuno-rog/CRIATURA-3-Retono-de-Cthulhu-733x1024_upse4d.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Enfermedad"
    ]
  },
  {
    "id": "1766788675840",
    "name": "Alazul",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422306/neptuno-rog/CRIATURA-4-Alazul-733x1024_df8j9e.webp",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Enfermedad",
      "Inicio del turno",
      "inflinjo",
      "Pierdo",
      "Vida"
    ]
  },
  {
    "id": "1766788753894",
    "name": " Geizhar",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422306/neptuno-rog/CRIATURA-4-Geizhar-733x1024_rppapm.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Campo",
      "Enfermedad"
    ]
  },
  {
    "id": "1766788834186",
    "name": "Tesorero James",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422307/neptuno-rog/CRIATURA-4-Tesorero-james-733x1024_rze5ly.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Cofre Codicia",
      "Cofre pesado",
      "Daño",
      "invocar",
      "Toque mortal"
    ]
  },
  {
    "id": "1766788874934",
    "name": "Averno, El Antiguo",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422307/neptuno-rog/CRIATURA-6-Averno-el-Antiguo-733x1024_eoveaz.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Cofre Codicia",
      "invocar"
    ]
  },
  {
    "id": "1766788925038",
    "name": "Elegida de Neptuno",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422308/neptuno-rog/CRIATURA-7-Elegida-de-Neptuno-733x1024_edopdm.webp",
    "factionCost": 4,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Creo",
      "Cofre Codicia",
      "Cofre pesado",
      "Escudo mágico",
      "Gano",
      "Mano"
    ]
  },
  {
    "id": "1766788971847",
    "name": "Kraken",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422308/neptuno-rog/CRIATURA-8-Kraken-733x1024_gz45v3.webp",
    "factionCost": 4,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Aniquilar",
      "Asalto",
      "Caída libre",
      "Pierdo",
      "Vida"
    ]
  },
  {
    "id": "1766789047956",
    "name": "Templo de R’lyeh",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422309/neptuno-rog/ESTRUCTURA-3-Templo-733x1024_jjdv4j.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Anulo",
      "Aturdir",
      "Criatura",
      "Enemiga",
      "Sello",
      "Todas"
    ]
  },
  {
    "id": "1766789101348",
    "name": "Tifón Ráfaga",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422311/neptuno-rog/MAGIA-RAPIDA-0-Tifon-Rafaga-733x1024_lv4y4c.webp",
    "factionCost": 0,
    "cost": 0,
    "banned": true,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Anulo",
      "Criatura",
      "Mover",
      "Sello"
    ]
  },
  {
    "id": "1766789180490",
    "name": "Ecos de Gruta",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422309/neptuno-rog/MAGIA-LENTA-3-Ecos-de-Gruta-733x1024_vsguvp.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Cargar",
      "invocar",
      "Provocar",
      "Selecciona",
      "Token"
    ]
  },
  {
    "id": "1766789220618",
    "name": "Pesadilla",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422310/neptuno-rog/MAGIA-LENTA-4-Pesadilla-733x1024_pzlscf.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Destruyo",
      "Enemiga",
      "Sacrificar"
    ]
  },
  {
    "id": "1766789257910",
    "name": "Avaricia",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422310/neptuno-rog/MAGIA-LENTA-6-Avaricia-733x1024_jxyhud.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Caída libre",
      "Cofre Codicia",
      "invocar"
    ]
  },
  {
    "id": "1766789292798",
    "name": "Peste de alquitrán",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422311/neptuno-rog/MAGIA-LENTA-6-Peste-de-Alquitran-733x1024_ikyu9e.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Campo",
      "Enfermedad",
      "inflinjo"
    ]
  },
  {
    "id": "1766789333061",
    "name": "Profecía maldita:",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422310/neptuno-rog/MAGIA-LENTA-3-Profecia-Maldita-733x1024_bilkr5.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adivinar",
      "Carta",
      "Criatura",
      "Mezclo",
      "Robar",
      "Sacrificar"
    ]
  },
  {
    "id": "1766789382460",
    "name": "Cofre Codicia",
    "faction": "neptuno",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422314/neptuno-rog/TOKEN-1-Cofre-Codicia-733x1024_dwd4by.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "invocar",
      "Robar",
      "Token"
    ]
  },
  {
    "id": "1766789425674",
    "name": "Cofre Pesado",
    "faction": "neptuno",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422314/neptuno-rog/TOKEN-3-Cofre-Pesado-733x1024_wnkqyz.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adelante",
      "Asalto",
      "Aturdir",
      "Criatura",
      "Enemiga",
      "Token"
    ]
  },
  {
    "id": "1766789484728",
    "name": "Lodo arcaico",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422303/neptuno-rog/ARTEFACTO-2-Lodo-Arcaico-733x1024_xpgtkw.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": true,
    "isEstructure": false,
    "tags": [
      "Aturdir",
      "Criatura",
      "Equipado",
      "Inicio del turno",
      "Pagar",
      "Sello"
    ]
  },
  {
    "id": "1766792362558",
    "name": "Bocadillo de Naar",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422303/neptuno-rog/Criatura-1-Bocadillo-de-Naar-733x1024_cowopo.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Enfermedad",
      "inflinjo",
      "Provocar",
      "Último suspiro"
    ]
  },
  {
    "id": "1766792406580",
    "name": "Plomo de James",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422309/neptuno-rog/MAGIA-LENTA-2-Plomo-de-James-733x1024_gwdhzc.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Daño",
      "Enfermedad",
      "inflinjo"
    ]
  },
  {
    "id": "1766792441900",
    "name": "Ritual Profano",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422309/neptuno-rog/MAGIA-LENTA-2-Ritual-Profano-733x1024_tew5ez.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Busco",
      "Mano",
      "Mazo"
    ]
  },
  {
    "id": "1766792485888",
    "name": "Mal Augurio",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422310/neptuno-rog/MAGIA-LENTA-3-Mal-Augurio-733x1024_en7ugt.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "aliada",
      "Criatura",
      "Toque mortal"
    ]
  },
  {
    "id": "1766792560530",
    "name": "Chef de Innsmouth",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422304/neptuno-rog/CRIATURA-3-Chef-de-Innsmouth-733x1024_l1muad.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Cofre Codicia",
      "Cofre pesado",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1766792598910",
    "name": "Sepultutrero de Innsmouth",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422305/neptuno-rog/Criatura-3-Sepulturero-de-Innsmouth-733x1024_m8uzbt.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adelante",
      "Aniquilar",
      "Criatura",
      "Último suspiro"
    ]
  },
  {
    "id": "1766792658308",
    "name": "Myk Hell's",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422307/neptuno-rog/CRIATURA-5-MYK-HELLE-1-733x1024_s2xzuc.webp",
    "factionCost": 2,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Aniquilar",
      "Asalto",
      "Criatura",
      "Enfermedad",
      "Enemiga",
      "Selecciona"
    ]
  },
  {
    "id": "1766792718406",
    "name": "Habitante de G'll-Hoo",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422307/neptuno-rog/CRIATURA-5-Habitante-current-1-733x1024_rdnmfo.webp",
    "factionCost": 2,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Cofre Codicia",
      "Cofre pesado",
      "Estoy en el campo",
      "Todas",
      "Toque mortal"
    ]
  },
  {
    "id": "1766792751675",
    "name": "Uxxia de Innsmouth",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422308/neptuno-rog/CRIATURA-6-uxxia-733x1024_fwdjwg.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Caída libre",
      "Provocar",
      "Toque mortal"
    ]
  },
  {
    "id": "1766792814038",
    "name": "Neptuno, Dios Cthulhu",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422308/neptuno-rog/Criatura-10-Neptuno-Dios-Cthulhu-no-full-art-733x1024_zzwvzg.webp",
    "factionCost": 5,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Enfermedad",
      "Escudo mágico",
      "inflinjo",
      "Mover"
    ]
  },
  {
    "id": "1766792850906",
    "name": "Brillante fortuna",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422310/neptuno-rog/MAGIA-LENTA-4-Brillante-Fortuna-733x1024_uwi7b9.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Creo",
      "Cofre Codicia",
      "Cofre pesado",
      "Mano"
    ]
  },
  {
    "id": "1766792924470",
    "name": "Guardían de R'lyeh",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422306/neptuno-rog/CRIATURA-4-Guardian-de-Rlyeh--733x1024_zjtjsd.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Daño",
      "Destruyo",
      "Gano",
      "inflinjo"
    ]
  },
  {
    "id": "1766792964850",
    "name": "Trabajadoe del Muelle",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422303/neptuno-rog/CRIATURA-1-Trabajador-del-Muelle-733x1024_fzet0i.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Creo",
      "Cofre pesado",
      "Mano",
      "Último suspiro"
    ]
  },
  {
    "id": "1766792988246",
    "name": "Sumpall Marea Negra",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422306/neptuno-rog/CRIATURA-3-Sumpall-Marea-negra-733x1024_glbjhi.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Toque mortal"
    ]
  },
  {
    "id": "1766793033244",
    "name": "Cofre Cascarudo",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422305/neptuno-rog/Criatura-3-Cofre-Cascarudo-733x1024_jzs9ua.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Creo",
      "Cofre Codicia",
      "Mano",
      "Mezclo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766793073212",
    "name": "Jaksalade",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422307/neptuno-rog/CRIATURA-5-Jaksalade-733x1024_dpmeo7.webp",
    "factionCost": 2,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adivinar",
      "Asalto",
      "Mazo"
    ]
  },
  {
    "id": "1766793124046",
    "name": "Semilla de Tifón",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422309/neptuno-rog/MAGIA-LENTA-1-Semilla-de-Tifon-733x1024_byu7ij.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Mover"
    ]
  },
  {
    "id": "1766793174226",
    "name": "Horror del Pantano",
    "faction": "neptuno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422304/neptuno-rog/CRIATURA-2-Horror-del-Pantano-733x1024_mj36fb.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Campo",
      "Creo",
      "Cofre pesado",
      "invocar",
      "Oponente"
    ]
  },
  {
    "id": "1766793217098",
    "name": "Paz'vi, Ancestro del Fin",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422305/neptuno-rog/CRIATURA-3-Paxvi-733x1024_jfbjgb.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Enfermedad",
      "inflinjo"
    ]
  },
  {
    "id": "1766793277494",
    "name": "Caicai Vilu",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422308/neptuno-rog/CRIATURA-8-CaiCai-Vilu-733x1024_al0xnt.webp",
    "factionCost": 4,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Enemiga",
      "otorgo",
      "Pierdo",
      "Vida"
    ]
  },
  {
    "id": "1766793333702",
    "name": "Barbañaraz, El Olvidado",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422306/neptuno-rog/CRIATURA-4-Barba-733x1024_plnqdg.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Cofre Codicia",
      "Cofre pesado",
      "Gano",
      "invocar"
    ]
  },
  {
    "id": "1766793417848",
    "name": "Maldición dee G'll-Hoo",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422311/neptuno-rog/Neptuno-45-Maldicion-de-Gll-Hoo-733x1024_o8mpmx.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": true,
    "isEstructure": false,
    "tags": [
      "Al atacar",
      "Criatura",
      "Enfermedad",
      "Equipado",
      "Obtengo"
    ]
  },
  {
    "id": "1766793455001",
    "name": "Bocadillo Oscuro",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422311/neptuno-rog/Neptuno-46-Bocadillo-Oscuro-733x1024_ywrw0v.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Criatura",
      "Enfermedad",
      "inflinjo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766793502622",
    "name": "Piraña Corrosiva ",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422311/neptuno-rog/Neptuno-47-Pirana-corrosiva-733x1024_gnkbt7.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Al atacar",
      "Creo",
      "Cofre Codicia",
      "Mazo",
      "Mezclo"
    ]
  },
  {
    "id": "1766793562158",
    "name": "Blob",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422312/neptuno-rog/Neptuno-48-Blob-733x1024_qo6iwy.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Enfermedad",
      "Gano",
      "Robar"
    ]
  },
  {
    "id": "1766793606584",
    "name": "Retoño de Kraken",
    "faction": "neptuno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422312/neptuno-rog/Neptuno-49-Retono-de-Kraken-733x1024_kmf5td.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Caída libre",
      "Criatura",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1766793656016",
    "name": "Acechante del Mal",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422312/neptuno-rog/Neptuno-50-Acechante-Nocturno-733x1024_lsfbvg.webp",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Daño",
      "inflinjo",
      "Selecciona",
      "Toque mortal"
    ]
  },
  {
    "id": "1766793729066",
    "name": "Emisario del Mar Negro",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422313/neptuno-rog/Neptuno-51-Emisario-del-Mar-Negro-733x1024_cd8n0h.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adivinar",
      "Asalto",
      "Descarto",
      "Mazo"
    ]
  },
  {
    "id": "1766793771648",
    "name": "Midas, Rey Olvidado",
    "faction": "neptuno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422313/neptuno-rog/Neptuno-52-Midas-Rey-Olvidado-733x1024_lmpvus.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Creo",
      "Cofre Codicia",
      "Cofre pesado",
      "Mano",
      "Venganza"
    ]
  },
  {
    "id": "1766793840056",
    "name": "Trempulcahue",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422313/neptuno-rog/Neptuno-53-Trempulcahue-733x1024_wf4jwh.webp",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adivinar",
      "Asalto",
      "Descarto",
      "Mazo",
      "Ordenar",
      "Toque mortal"
    ]
  },
  {
    "id": "1766793905632",
    "name": "Trempul de Conquista",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422313/neptuno-rog/Neptuno-54-Trempul-de-Conquista-733x1024_oz0vmi.webp",
    "factionCost": 4,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Campo",
      "Cofre Codicia",
      "Provocar"
    ]
  },
  {
    "id": "1766793939296",
    "name": "Dagon",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422313/neptuno-rog/Neptuno-55-Dagon-733x1024_h68uyo.webp",
    "factionCost": 4,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Aniquilar",
      "Asalto",
      "Criatura",
      "Gano"
    ]
  },
  {
    "id": "1766793968554",
    "name": "Toque de Midas",
    "faction": "neptuno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422314/neptuno-rog/Neptuno-56-Toque-de-Midas-733x1024_wn2skm.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Cofre Codicia",
      "Transformar"
    ]
  }
]
