import { Card } from "src/app/interfaces/card.interface";

export const PLUTON_CARDS: Card[] =[
  {
    "id": "1766779770242",
    "name": "Sello Pluton",
    "faction": "pluton",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344853/pluton-rog/SELLO-de-Pluton-733x1024_eu9duo.webp",
    "factionCost": 0,
    "cost": 0,
    "banned": false,
    "isSeal": true,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": []
  },
  {
    "id": "1766779829778",
    "name": "Ruego Oculto",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344781/pluton-rog/CRIATURA-1-Ruego-Oculto-733x1024_ugd2tn.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Campo",
      "Mazo",
      "Sello",
      "Último suspiro"
    ]
  },
  {
    "id": "1766779881334",
    "name": "Cultista Sacrílego",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344783/pluton-rog/CRIATURA-2-Cultista-Sacrilego-733x1024_p5tjai.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Carta",
      "Robar",
      "Último suspiro"
    ]
  },
  {
    "id": "1766779931868",
    "name": "Arlequín Fantasma",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344782/pluton-rog/CRIATURA-2-Arlequin-Fantasma-733x1024_avj3gw.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Mover",
      "Puñalada"
    ]
  },
  {
    "id": "1766780031528",
    "name": "El ilusionista",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344833/pluton-rog/Marca-de-agua-2-733x1024_vqyyqy.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Carta",
      "Descarto",
      "Robar",
      "Último suspiro"
    ]
  },
  {
    "id": "1766780095052",
    "name": "Gomushi",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344789/pluton-rog/CRIATURA-3-Gomushi-733x1024_mi4qeg.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "Ataque rápido",
      "Carta",
      "Destruyo",
      "Descarto",
      "Mazo",
      "Oponente"
    ]
  },
  {
    "id": "1766780192662",
    "name": "El murmurador",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344793/pluton-rog/CRIATURA-4-El-Murmurador-733x1024_yopksz.webp",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Coste",
      "Pagar",
      "Revivo",
      "Silencio",
      "Token",
      "Vida"
    ]
  },
  {
    "id": "1766780249440",
    "name": "Fetch,, El Carcelero",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344798/pluton-rog/CRIATURA-5-Fetch-El-Carcelero-733x1024_ll5wxr.webp",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Carta",
      "Mano",
      "Oponente",
      "Revelar",
      "Selecciona"
    ]
  },
  {
    "id": "1766780329860",
    "name": "Nether",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344798/pluton-rog/CRIATURA-5-Nether-733x1024_feaw5x.webp",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Carta",
      "Descarto",
      "Mano",
      "Mazo",
      "Oponente",
      "Revelar"
    ]
  },
  {
    "id": "1766780412576",
    "name": "Plutón: El dios envidioso",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344800/pluton-rog/CRIATURA-5-Pluton-Dios-Oscuro-733x1024_a9k5bl.webp",
    "factionCost": 4,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "Asalto",
      "Carta",
      "Descarto",
      "Mazo",
      "Mezclo",
      "Oponente",
      "Robar"
    ]
  },
  {
    "id": "1766780481386",
    "name": "Elegido de Plutón",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344804/pluton-rog/CRIATURA-6-Elegido-de-Pluton-733x1024_qmzcjo.webp",
    "factionCost": 4,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Carta",
      "Descarto",
      "Mano",
      "Mazo",
      "Oponente",
      "Revelar",
      "Robar",
      "Vida"
    ]
  },
  {
    "id": "1766780554094",
    "name": "Inferno",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344813/pluton-rog/MAGIA-LENTA-0-Inferno-733x1024_rhnslj.webp",
    "factionCost": 0,
    "cost": 0,
    "banned": true,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Campo",
      "Carta",
      "Criatura",
      "Daño",
      "Descarto",
      "inflinjo",
      "Sello"
    ]
  },
  {
    "id": "1766780763808",
    "name": "Desdén sacrílego",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344809/pluton-rog/ESTRUCTURA-3-Desden-Sacrilego-733x1024_tryug8.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": true,
    "tags": [
      "Carta",
      "Criatura",
      "Descarto",
      "inflinjo",
      "Oponente",
      "Robar"
    ]
  },
  {
    "id": "1766784413498",
    "name": "Cañón de Zagh",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344810/pluton-rog/ESTRUCTURA-4-Canon-de-Zagh-733x1024_furfqt.webp",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Campo",
      "Escudo mágico",
      "Mazo",
      "Sello",
      "Vida"
    ]
  },
  {
    "id": "1766784481670",
    "name": "Ratonera",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344815/pluton-rog/MAGIA-LENTA-2-Ratonera-733x1024_l14ruv.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Descarto",
      "Mezclo",
      "Oponente",
      "Sello"
    ]
  },
  {
    "id": "1766784532030",
    "name": "Información privilegiada",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344820/pluton-rog/MAGIA-LENTA-4-Informacion-Privilegiada-733x1024_ldujpb.webp",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Descarto",
      "Mano",
      "Oponente",
      "Revelar",
      "Sobrecarga"
    ]
  },
  {
    "id": "1766784640132",
    "name": "Artimaña vil",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344821/pluton-rog/MAGIA-LENTA-5-Artimana-Vil-733x1024_xoxbye.webp",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Selecciona",
      "Token",
      "Transformar"
    ]
  },
  {
    "id": "1766784730958",
    "name": "Robo de alma",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344824/pluton-rog/MAGIA-LENTA-6-Robo-de-Alma-733x1024_e1sth4.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Coste",
      "Mano",
      "Oponente",
      "Reducir",
      "Revelar",
      "Robar",
      "Sello"
    ]
  },
  {
    "id": "1766784811294",
    "name": "Señor de las tinieblas",
    "faction": "pluton",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344854/pluton-rog/TOKEN-Senor-de-las-Tinieblas-733x1024_fn60ek.webp",
    "factionCost": 5,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Anulo",
      "Asalto",
      "Carta",
      "Daño",
      "Enemiga",
      "inflinjo",
      "Mezclo",
      "no puede",
      "Robar"
    ]
  },
  {
    "id": "1766784878264",
    "name": "Chasquido",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344828/pluton-rog/MAGIA-RAPIDA-1-Chasquido-733x1024_px6ocs.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Daño",
      "Descarto",
      "inflinjo",
      "Mano",
      "Oponente"
    ]
  },
  {
    "id": "1766785035558",
    "name": "Demagogia",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344829/pluton-rog/MAGIA-RAPIDA-3-Demagogia-733x1024_sdgul6.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Anulo",
      "Criatura",
      "Magia",
      "Sello"
    ]
  },
  {
    "id": "1766785146270",
    "name": "Traición",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344832/pluton-rog/MAGIA-RAPIDA-3-Traicion-733x1024_zojm08.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Anulo",
      "Criatura",
      "Daño",
      "Oponente",
      "Vida"
    ]
  },
  {
    "id": "1766785213030",
    "name": "Chovy",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344781/pluton-rog/CRIATURA-1-Chovy-733x1024_cd5yeb.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Descarto",
      "Mazo",
      "Oponente",
      "Último suspiro"
    ]
  },
  {
    "id": "1766785281204",
    "name": "¡Revolución!",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344817/pluton-rog/MAGIA-LENTA-3-_Revolucion-733x1024_bcddbb.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Criatura",
      "Daño",
      "inflinjo"
    ]
  },
  {
    "id": "1766785354272",
    "name": "Mago de La Galera",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344790/pluton-rog/CRIATURA-3-Mago-de-la-Galera-733x1024_dcppk2.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "aliada",
      "Criatura",
      "Enemiga",
      "Mover"
    ]
  },
  {
    "id": "1766785407690",
    "name": "Nube",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344791/pluton-rog/CRIATURA-3-Nube-1-733x1024_jeaspj.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Criatura",
      "Destruyo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766785479544",
    "name": "Espejo en la  Pared",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344830/pluton-rog/MAGIA-RAPIDA-3-Espejo-en-la-pared-733x1024_mpjaoi.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Aniquilar",
      "Carta",
      "Criatura",
      "Enemiga",
      "Respuesta"
    ]
  },
  {
    "id": "1766785551492",
    "name": "KHA R'LOSS",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344794/pluton-rog/CRIATURA-4-Khar-Los-733x1024_bczxvm.webp",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Cementerio",
      "Revivo"
    ]
  },
  {
    "id": "1766785693218",
    "name": "Príncipe Ingenioso",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344796/pluton-rog/CRIATURA-4-Principe-Ingenioso-733x1024_fue8hs.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Descarto",
      "Oponente",
      "Robar"
    ]
  },
  {
    "id": "1766785767714",
    "name": "Morgana",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344795/pluton-rog/CRIATURA-4-Morgana-1-733x1024_qhsxre.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Aniquilar",
      "Carta",
      "Descarto",
      "Robar",
      "Último suspiro"
    ]
  },
  {
    "id": "1766785856640",
    "name": "Espadachín Fantasma",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344805/pluton-rog/CRIATURA-6-Espadachin-fantasma-733x1024_okqxqa.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Detras",
      "invocar",
      "Puñalada"
    ]
  },
  {
    "id": "1766785925097",
    "name": "Mortazar",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344806/pluton-rog/CRIATURA-7-Mortazar-733x1024_d45jzm.webp",
    "factionCost": 4,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Descarto",
      "Mano",
      "Oponente",
      "Robar",
      "Selecciona"
    ]
  },
  {
    "id": "1766786017034",
    "name": "Nail, Secuaz de Fetch",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344788/pluton-rog/CRIATURA-2-Nail-733x1024_qa5rdn.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Atrapo",
      "Carta",
      "Criatura",
      "Mazo",
      "Mezclo",
      "Oponente",
      "Revelar",
      "Robar"
    ]
  },
  {
    "id": "1766786072738",
    "name": "Profanador del Castillo",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344801/pluton-rog/CRIATURA-5-Profanador-del-Castillo-733x1024_utn4wq.webp",
    "factionCost": 1,
    "cost": 4,
    "banned": true,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Daño",
      "Descarto",
      "Mazo",
      "Oponente",
      "Provocar"
    ]
  },
  {
    "id": "1766786155522",
    "name": "Alborotador",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344780/pluton-rog/CRIATURA-1-Alborotador-733x1024_cz9y9w.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Atrapo",
      "Carta",
      "Mano",
      "Oponente"
    ]
  },
  {
    "id": "1766786220764",
    "name": "Monstruo Del Armario",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344786/pluton-rog/CRIATURA-2-Monstruo-del-Armario-733x1024_avntud.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Comerciable",
      "Descarto",
      "Mazo",
      "mejora",
      "Oponente",
      "Último suspiro"
    ]
  },
  {
    "id": "1766786290828",
    "name": "Lich del Catillo",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344785/pluton-rog/CRIATURA-2-Lich-del-casillo-733x1024_vsnftq.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Busco",
      "Cementerio",
      "Mano",
      "Mazo",
      "Revelar",
      "Último suspiro"
    ]
  },
  {
    "id": "1766786367738",
    "name": "Plegaria a las Tinieblas",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344814/pluton-rog/MAGIA-LENTA-2-Plegaria-a-las-tinieblas-733x1024_e75lte.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "aliada",
      "Carta",
      "Criatura",
      "Mano",
      "Oponente",
      "Selecciona"
    ]
  },
  {
    "id": "1766786459207",
    "name": "Picardia Imp",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344827/pluton-rog/MAGIA-RAPIDA-2-Picardia-Imp-733x1024_owwitc.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Anulo",
      "Carta",
      "Coste",
      "Devuelvo",
      "Mano",
      "Magia"
    ]
  },
  {
    "id": "1766786561908",
    "name": "Astaroth, Presagio del Apocalipsis",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344808/pluton-rog/CRIATURA-8-Astaroth-733x1024_btqqkt.webp",
    "factionCost": 5,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Daño",
      "inflinjo",
      "Todas"
    ]
  },
  {
    "id": "1766786676776",
    "name": "Explosíon Necrótica",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344826/pluton-rog/MAGIA-RAPIDA-2-Explosion-Necrotica-733x1024_b4jnxl.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Criatura",
      "Daño",
      "inflinjo",
      "Robar"
    ]
  },
  {
    "id": "1766786784800",
    "name": "Pacto Tenebroso",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344819/pluton-rog/MAGIA-LENTA-3-Pacto-Tenebroso-733x1024_s6fskc.webp",
    "factionCost": 3,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Descarto",
      "Mano",
      "Oponente",
      "Vida"
    ]
  },
  {
    "id": "1766786853676",
    "name": "El Señor de la Noche",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344784/pluton-rog/CRIATURA-2-ESDLN-733x1024_x7nvpk.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Asalto",
      "Cambio",
      "Criatura",
      "Posicion"
    ]
  },
  {
    "id": "1766786970640",
    "name": "Domador Infernal",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344803/pluton-rog/CRIATURA-6-Domador-Infernal-733x1024_tqpsta.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Adelante",
      "Atras",
      "Asalto",
      "Creo"
    ]
  },
  {
    "id": "1766787076594",
    "name": "Caja de Desilusiones",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344835/pluton-rog/Pluton-45-Caja-de-Desilusiones-733x1024_t5beyj.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Descarto",
      "Mano",
      "Ofrenda tenebrosa",
      "Robar"
    ]
  },
  {
    "id": "1766787143920",
    "name": "Bibliotecario",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344836/pluton-rog/Pluton-46-Bibliotecario-Maldito-733x1024_kaactw.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Descarto",
      "Ofrenda tenebrosa"
    ]
  },
  {
    "id": "1766787274044",
    "name": "Acólito de la Cripta",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344838/pluton-rog/Pluton-47-Acolito-de-la-Cripta-733x1024_lcvwpw.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Intercambio",
      "Vida"
    ]
  },
  {
    "id": "1766787350430",
    "name": "El Cronador del Castillo",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344839/pluton-rog/Pluton-48-Cronador-del-Castillo-733x1024_ztbfqp.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Jugar",
      "Magia"
    ]
  },
  {
    "id": "1766787416080",
    "name": "Fetch Ascendido",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344840/pluton-rog/Pluton-49-Fetch-ascendido-733x1024_hyd6x1.webp",
    "factionCost": 3,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Aniquilar",
      "Asalto",
      "Carta",
      "Gano"
    ]
  },
  {
    "id": "1766787512466",
    "name": "Orochi Daga Oscura",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344844/pluton-rog/Pluton-50-Orochi-733x1024_dpxr1q.webp",
    "factionCost": 4,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Alrededor",
      "Criatura",
      "Daño",
      "Enemiga",
      "inflinjo",
      "Ofrenda tenebrosa",
      "Teletransporto"
    ]
  },
  {
    "id": "1766787594960",
    "name": "Profanador Ruin",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344844/pluton-rog/Pluton-51-Profanador-Ruin-733x1024_ayk64h.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Aniquilar",
      "Asalto",
      "Atrapo",
      "Carta",
      "Daño",
      "Mazo",
      "Oponente",
      "Provocar"
    ]
  },
  {
    "id": "1766787694490",
    "name": "Lugarteniente de Plutón",
    "faction": "pluton",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344845/pluton-rog/Pluton-52-Lugarteniente-de-Pluton-733x1024_lrdzle.webp",
    "factionCost": 2,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Coste",
      "invocar",
      "Ofrenda tenebrosa"
    ]
  },
  {
    "id": "1766787747776",
    "name": "Onny God-Born",
    "faction": "pluton",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344847/pluton-rog/Pluton-53-Onny-God-Born-733x1024_eul4vl.webp",
    "factionCost": 4,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Ofrenda tenebrosa",
      "Robar",
      "Vida"
    ]
  },
  {
    "id": "1766787791608",
    "name": "Rebeck, Sonata Oscura",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344849/pluton-rog/Pluton-54-Rebeck-Sonata-Oscura-733x1024_ht6nob.webp",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Al atacar",
      "Descarto",
      "Enemiga",
      "Mazo"
    ]
  },
  {
    "id": "1766787851104",
    "name": "Final Fantasma",
    "faction": "pluton",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344850/pluton-rog/Pluton-55-Final-Fantasma-733x1024_v9rant.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "tags": [
      "Carta",
      "Descarto",
      "invocar",
      "Oponente",
      "Sobrecarga",
      "Token"
    ]
  },
  {
    "id": "1766787900413",
    "name": "Devora-Almas",
    "faction": "pluton",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766344851/pluton-rog/Pluton-56-Devora-almas-733x1024_y0ntzr.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": true,
    "isEstructure": false,
    "tags": [
      "Al golpear",
      "Criatura",
      "Daño",
      "inflinjo"
    ]
  }
]
