import { Card } from "src/app/interfaces/card.interface";

export const SATURNO_CARDS: Card[] =[
  {
    "id": "1766794243302",
    "name": "Sello Saturno",
    "faction": "saturno",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766794217/saturno-rog/sello-saturno_u5mmqz.jpg",
    "factionCost": 0,
    "cost": 0,
    "banned": false,
    "isSeal": true,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "tags": []
  },
  {
    "id": "1766794288512",
    "name": "Propiedad Privada",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422353/saturno-rog/TERRENO-1-Prop-733x1024_r1evkw.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": true,
    "tags": [
      "Terreno"
    ]
  },
  {
    "id": "1766794679172",
    "name": "Jefe Contratista",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422340/saturno-rog/CRIATURA-1-Jefe-Contratista-733x1024_uomapp.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Cerco electrico",
      "Creo",
      "Mano",
      "Terreno",
      "Último suspiro"
    ]
  },
  {
    "id": "1766794778506",
    "name": "Juego de Títeres",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422346/saturno-rog/MAGIA-LENTA-2-Juego-de-Titeres-733x1024_lcjyrl.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Casillero",
      "Criatura",
      "Daño",
      "Enemiga",
      "inflinjo",
      "Mover"
    ]
  },
  {
    "id": "1766794874963",
    "name": "Esmeralda",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422341/saturno-rog/CRIATURA-2-Esmeralda-733x1024_wshvjh.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Carta",
      "Robar",
      "Último suspiro"
    ]
  },
  {
    "id": "1766794939686",
    "name": "Ben Dehumo",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422340/saturno-rog/CRIATURA-2-Ben-Dehumo-733x1024_c6x6aj.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Cerco electrico",
      "Coste",
      "Reducir"
    ]
  },
  {
    "id": "1766794969865",
    "name": "Amo de Llaves",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422340/saturno-rog/CRIATURA-2-Amo-de-Llaves-733x1024_sybkat.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Cerco electrico",
      "Creo",
      "Mano"
    ]
  },
  {
    "id": "1766795031970",
    "name": "Cerco Eléctrico",
    "faction": "saturno",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422353/saturno-rog/TOKEN-TERRENO-2-Cerco-Electrico-733x1024_jyflys.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": true,
    "tags": [
      "Daño",
      "Finalizar",
      "inflinjo"
    ]
  },
  {
    "id": "1766795100616",
    "name": "Miameee",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422353/saturno-rog/TERRENO-2-MIAMEEE-733x1024_gegz3k.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": true,
    "tags": [
      "Casillero",
      "Carta",
      "Coste",
      "Destruyo",
      "Reducir"
    ]
  },
  {
    "id": "1766795154100",
    "name": "Plan Maestro",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422346/saturno-rog/MAGIA-LENTA-2-Plan-Maestro-733x1024_jxmdu7.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "aliada",
      "Carta",
      "Devuelvo",
      "Mano",
      "Robar",
      "Terreno"
    ]
  },
  {
    "id": "1766795207172",
    "name": "Oetam Ansillam",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422341/saturno-rog/CRIATURA-2-Oetam-Ansillam-1-733x1024_ww84s2.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Carta",
      "Cerco electrico",
      "Creo",
      "Mano",
      "Robar"
    ]
  },
  {
    "id": "1766795245675",
    "name": "Pandemia Intencional",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422347/saturno-rog/MAGIA-LENTA-4-Pandemia-Intencional-733x1024_vicqv0.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Criatura",
      "Daño",
      "inflinjo",
      "Todas"
    ]
  },
  {
    "id": "1766795291204",
    "name": "Capitalización",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422348/saturno-rog/MAGIA-RAPIDA-3-Capitalizacion-733x1024_hwyqhj.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Daño",
      "Inmune"
    ]
  },
  {
    "id": "1766795357149",
    "name": "Control Político",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422346/saturno-rog/MAGIA-LENTA-3-Control-Politico-733x1024_at5hwx.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Criatura",
      "Devuelvo",
      "Oponente",
      "Sobrecarga"
    ]
  },
  {
    "id": "1766795393350",
    "name": "Botín presidencial",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422346/saturno-rog/MAGIA-LENTA-2-Botin-Presidencial-733x1024_bnypca.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Adivinar",
      "Ordenar"
    ]
  },
  {
    "id": "1766795443370",
    "name": "Bagy, Master Trader",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422341/saturno-rog/CRIATURA-3-Baggy-Dios-del-Trade-733x1024_ghciuw.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Daño",
      "Terreno"
    ]
  },
  {
    "id": "1766795493648",
    "name": "Cisne Negro",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422347/saturno-rog/MAGIA-LENTA-4-Cisne-Negro-733x1024_oavtef.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Campo",
      "Cerco electrico",
      "Creo",
      "Mazo",
      "Sello"
    ]
  },
  {
    "id": "1766795546338",
    "name": "Influencer Inalcanzable",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422344/saturno-rog/CRIATURA-4-Influencer-733x1024_yetkmz.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Carta",
      "Criatura",
      "Oponente",
      "Revelar"
    ]
  },
  {
    "id": "1766795611372",
    "name": "Mansíon Opulenta",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422345/saturno-rog/ESTRUCTURA-5-Mansion-Opulenta-2-733x1024_llugnb.webp",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": true,
    "isTerreno": false,
    "tags": [
      "Carta",
      "Inicio del turno",
      "Robar"
    ]
  },
  {
    "id": "1766795659548",
    "name": "Juez Corupto",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422344/saturno-rog/CRIATURA-6-Juez-Corrupto-733x1024_uwevxd.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Daño",
      "inflinjo",
      "Terreno"
    ]
  },
  {
    "id": "1766795700481",
    "name": "Margareth Ibai",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422345/saturno-rog/CRIATURA-6-Margareth-1-733x1024_lkum3z.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Gano",
      "Terreno"
    ]
  },
  {
    "id": "1766795744561",
    "name": "Elegido de Saturno",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422345/saturno-rog/CRIATURA-8-Elegido-de-Saturno-1-733x1024_hymrad.webp",
    "factionCost": 2,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Comerciable",
      "Escudo mágico",
      "Gano",
      "mejora",
      "Terreno"
    ]
  },
  {
    "id": "1766795795860",
    "name": "El Mundo es Mío",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422347/saturno-rog/MAGIA-LENTA-8-El-mundo-es-mio-733x1024_ba3miy.webp",
    "factionCost": 3,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Comerciable",
      "Daño",
      "Destruyo",
      "mejora",
      "Terreno"
    ]
  },
  {
    "id": "1766795902008",
    "name": "Don Fettuccine",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422343/saturno-rog/CRIATURA-4-Don-Fettuccine-733x1024_excvuk.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Carta",
      "Mano",
      "Mazo",
      "Robar",
      "Una vez por turno"
    ]
  },
  {
    "id": "1766795955158",
    "name": "Ladrón de Joyas",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422342/saturno-rog/CRIATURA-3-Ladron-de-joyas-733x1024_funaw7.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "aliada",
      "Gano",
      "Terreno"
    ]
  },
  {
    "id": "1766796082410",
    "name": "Havivi, Maestro Ingeniero",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422344/saturno-rog/CRIATURA-6-Havivi-733x1024_spivia.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Casillero",
      "Cerco electrico",
      "Creo",
      "Provocar",
      "Último suspiro"
    ]
  },
  {
    "id": "1766796135511",
    "name": "Científico de la Orden",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422343/saturno-rog/CRIATURA-4-Cientifico-de-la-Orden-733x1024_nf216b.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Campo",
      "Daño",
      "inflinjo",
      "Terreno"
    ]
  },
  {
    "id": "1766796263134",
    "name": "Espantapobres",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422339/saturno-rog/CRIATURA-1-Espantapobres-733x1024_jtfgpq.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Anulo",
      "Asalto",
      "Oponente"
    ]
  },
  {
    "id": "1766796319596",
    "name": "Mayordomo de la Mansión",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422341/saturno-rog/CRIATURA-2-Mayordomo-733x1024_y95bhy.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Creo",
      "Mano",
      "Último suspiro"
    ]
  },
  {
    "id": "1766796362522",
    "name": "Cazador de Alta Cuna",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422342/saturno-rog/CRIATURA-3-Cazador-de-alta-alcurnia-733x1024_eslruc.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": true,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Destruyo",
      "Enemiga",
      "Gano"
    ]
  },
  {
    "id": "1766796400362",
    "name": "Clinton Criptas",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422342/saturno-rog/CRIATURA-3-Clinton-Criptas-733x1024_ufnycq.webp",
    "factionCost": 1,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Busco",
      "Mazo",
      "Terreno",
      "Último suspiro"
    ]
  },
  {
    "id": "1766796447555",
    "name": "Mona",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422343/saturno-rog/CRIATURA-3-Mona-733x1024_rtryer.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Enemiga",
      "Silencio"
    ]
  },
  {
    "id": "1766796504256",
    "name": "Gonzalo Delpalo",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422343/saturno-rog/CRIATURA-4-Gonzalo-DelPalo-733x1024_yalfdt.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Campo",
      "Devuelvo",
      "Mano",
      "Terreno"
    ]
  },
  {
    "id": "1766796549513",
    "name": "Medidas Desesperadas",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422348/saturno-rog/MAGIA-RAPIDA-4-Medidas-Desesperadas-733x1024_bjjvas.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Criatura",
      "Destruyo",
      "Sobrecarga",
      "Todas"
    ]
  },
  {
    "id": "1766796600917",
    "name": "Campos Desforestados",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422353/saturno-rog/TERRENO-1-Campos-desf-733x1024_luiwsd.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": true,
    "tags": [
      "Casillero",
      "Carta",
      "Destruyo",
      "Robar"
    ]
  },
  {
    "id": "1766796636032",
    "name": "Cleena Donna",
    "faction": "saturno",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422348/saturno-rog/Saturno-36-Cleena-Donna-733x1024_er2uaq.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Creo",
      "Mano",
      "Token",
      "Último suspiro"
    ]
  },
  {
    "id": "1766796683700",
    "name": "Doncella Carmesí",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422348/saturno-rog/Saturno-37-Doncella-Carmesi-733x1024_y7yj0i.webp",
    "factionCost": 1,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Criatura",
      "Drenar",
      "Enemiga",
      "Primera vez"
    ]
  },
  {
    "id": "1766796720153",
    "name": "Joyero de Fafner",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422349/saturno-rog/Saturno-38-Joyero-de-Fafner-733x1024_wqz2gw.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Creo",
      "Mazo",
      "Mezclo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766796763965",
    "name": "Cazador de Medianoche",
    "faction": "saturno",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422349/saturno-rog/Saturno-39-Cazador-de-Medianoche-733x1024_mp2w97.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Criatura",
      "Destruyo",
      "Gano"
    ]
  },
  {
    "id": "1766796807713",
    "name": "Baron Von Zukk",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422349/saturno-rog/Saturno-40-Baron-Von-Zukk-733x1024_iglw3v.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Criatura",
      "Drenar",
      "Enemiga",
      "Mover"
    ]
  },
  {
    "id": "1766796843777",
    "name": "matón de Ultratumba",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422350/saturno-rog/Saturno-41-Maton-de-Ultratumba-733x1024_mtkjsm.webp",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Gano",
      "Provocar",
      "Terreno"
    ]
  },
  {
    "id": "1766796898199",
    "name": "Dulce Lilith",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422350/saturno-rog/Saturno-42-Dulce-Lilith-733x1024_zzdskr.webp",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Alrededor",
      "Aniquilar",
      "Asalto",
      "Criatura"
    ]
  },
  {
    "id": "1766796936453",
    "name": "Maximilian Siniestro",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422350/saturno-rog/Saturno-43-Maximilian-Siniestro-733x1024_gkp4wg.webp",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "invocar",
      "Oponente",
      "Terreno",
      "Vida"
    ]
  },
  {
    "id": "1766796987907",
    "name": "Vanya, Reina Roja",
    "faction": "saturno",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422350/saturno-rog/Saturno-44-Vanya-Reina-Roja-733x1024_tbu33l.webp",
    "factionCost": 4,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Asalto",
      "Cerco electrico",
      "Creo",
      "Drenar",
      "Enemiga",
      "Mano",
      "Último suspiro"
    ]
  },
  {
    "id": "1766797074269",
    "name": "Palacio Faffner",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422351/saturno-rog/Saturno-45-Palacio-Faffner-733x1024_eurs8g.webp",
    "factionCost": 3,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": true,
    "isTerreno": false,
    "tags": [
      "Busco",
      "Mano",
      "Magia",
      "Revelar",
      "Sello"
    ]
  },
  {
    "id": "1766797113716",
    "name": "Garras del Conde",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422352/saturno-rog/Saturno-46-Garras-del-Conde-733x1024_z3gxdg.webp",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Criatura",
      "Mazo",
      "Mezclo",
      "Selecciona",
      "Vida"
    ]
  },
  {
    "id": "1766797160904",
    "name": "Transfusión de Sangre",
    "faction": "saturno",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422351/saturno-rog/Saturno-47-Transfusion-de-Sangre-733x1024_j93box.webp",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Carta",
      "Drenar",
      "Robar"
    ]
  },
  {
    "id": "1766797237010",
    "name": "Dama de Hierro",
    "faction": "saturno",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422352/saturno-rog/Saturno-48-Dama-de-Hierro-733x1024_gzu67v.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": true,
    "tags": [
      "Criatura",
      "Destruyo",
      "Drenar",
      "Enemiga",
      "Finalizar",
      "Terreno"
    ]
  },
  {
    "id": "1766797273994",
    "name": "Llave del Cronodragón",
    "faction": "saturno",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422352/saturno-rog/Saturno-49-LLave-del-Cronodragon-733x1024_pigiao.webp",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "isEstructure": false,
    "isTerreno": false,
    "tags": [
      "Carta",
      "Robar"
    ]
  }
]
