import { Card } from "src/app/interfaces/card.interface";

export const TIERRA_CARDS: Card[] = [
  {
    "id": "1766512385849",
    "name": "Sello",
    "faction": "tierra",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422415/tierra-rog/sello_snxdfi.png",
    "factionCost": 0,
    "cost": 0,
    "banned": false,
    "isSeal": true,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": []
  },
  {
    "id": "1766512486637",
    "name": "Cría Hambienta",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422358/tierra-rog/cria-hambrienta_ou71oc.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al atacar"
    ]
  },
  {
    "id": "1766512559911",
    "name": "Evolución Temprana",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422360/tierra-rog/evolucion-temprana_wzkedu.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Coste",
      "Daño",
      "Reducir"
    ]
  },
  {
    "id": "1766512664491",
    "name": "Furia Jurásica",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422361/tierra-rog/furia-jurasica_nwmufr.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "aliada",
      "Ataque rápido",
      "Criatura",
      "otorgo"
    ]
  },
  {
    "id": "1766512711472",
    "name": "Microceraptor",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422384/tierra-rog/microceraptor_clpjgd.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766512862901",
    "name": "Madre Vigilante",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422383/tierra-rog/madre-vigilante_dy8cap.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766512922499",
    "name": "Pisotón",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/pisoton_z9qlkn.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Destruyo"
    ]
  },
  {
    "id": "1766512977483",
    "name": "Velocompi Robaoros",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422441/tierra-rog/velocompi_bc4gjb.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Carta",
      "Robar"
    ]
  },
  {
    "id": "1766513037215",
    "name": "Elegida de Tierra",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422360/tierra-rog/ELEGIDA-DE-TIERRA_umwnwg.png",
    "factionCost": 3,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Busco",
      "Criatura",
      "Mano",
      "Revelar"
    ]
  },
  {
    "id": "1766513080049",
    "name": "Turok, tanque Viviente",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422441/tierra-rog/turok_jqbnvl.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Aturdir",
      "Criatura"
    ]
  },
  {
    "id": "1766513127481",
    "name": "Xiara, Guardacostas",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422442/tierra-rog/xiara_aratyw.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "curar",
      "Daño"
    ]
  },
  {
    "id": "1766513200671",
    "name": "Zigzagón, El Trotamundos",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422444/tierra-rog/zigzagon_oj5iq5.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "Diagonal",
      "huevo",
      "Mover",
      "Último suspiro"
    ]
  },
  {
    "id": "1766513391795",
    "name": "Escalodón Solar",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422360/tierra-rog/escalodon_ei0me0.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Mazo",
      "Sello",
      "Último suspiro"
    ]
  },
  {
    "id": "1766513441789",
    "name": "Griska, El Cercenador",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422362/tierra-rog/griska_nmtesj.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Carta",
      "Robar"
    ]
  },
  {
    "id": "1766513506249",
    "name": "Khar, Apetito Insaciable",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422379/tierra-rog/khar_y2lokl.png",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Ataque rápido",
      "Aturdir",
      "Enfermedad",
      "Inmune"
    ]
  },
  {
    "id": "1766513552453",
    "name": "Necrorex",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422386/tierra-rog/necrorex_smtsoz.png",
    "factionCost": 2,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "Creo",
      "Destruyo",
      "huevo"
    ]
  },
  {
    "id": "1766513604829",
    "name": "Pyronodon",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/pyrodon_lqjzkw.png",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Daño",
      "inflinjo",
      "Oponente"
    ]
  },
  {
    "id": "1766513663741",
    "name": "Tiranía de Gigantes",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422441/tierra-rog/tirania-de-gigantes_dlg2ze.png",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Destruyo"
    ]
  },
  {
    "id": "1766513706517",
    "name": "Titán Rompecielos",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422440/tierra-rog/titan-rompe-cielos_vgvnae.png",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766513814801",
    "name": "Yagor, Terror Prehistórico",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422443/tierra-rog/yagor_cjaaid.png",
    "factionCost": 4,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "Asalto",
      "Carta",
      "Criatura",
      "Gano",
      "Mazo",
      "Revelar"
    ]
  },
  {
    "id": "1766513878647",
    "name": "Zilagodon, Dios de la Tierra",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422444/tierra-rog/zilagodon_po1wl1.png",
    "factionCost": 5,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Criatura",
      "otorgo"
    ]
  },
  {
    "id": "1766513953557",
    "name": "Huevo Jurásico",
    "faction": "tierra",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422361/tierra-rog/huevo-jurasico_lt40wl.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Revivo",
      "Token"
    ]
  },
  {
    "id": "1766514060469",
    "name": "Sembrador del Mañana",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422443/tierra-rog/zembrador-del-manana_gzigwt.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Coste"
    ]
  },
  {
    "id": "1766514260487",
    "name": "Vigila-Crías",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422442/tierra-rog/vigila-crias_vy0jil.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Eclosiono",
      "otorgo"
    ]
  },
  {
    "id": "1766514560407",
    "name": "Bok Nubealta",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422358/tierra-rog/bok-nubealta_kqgpjs.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Caída libre"
    ]
  },
  {
    "id": "1766514604899",
    "name": "Impactador de Marea negra",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422362/tierra-rog/impactador-de-marea-negra_ouiypm.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Mover"
    ]
  },
  {
    "id": "1766514655547",
    "name": "Acarreador Enorme",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422357/tierra-rog/acarreador-enorrme_tqn32s.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Cargar",
      "Eclosiono"
    ]
  },
  {
    "id": "1766514741585",
    "name": "Mutante Tirano",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/mutante-tirano_gurehv.png",
    "factionCost": 4,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Copio",
      "Criatura"
    ]
  },
  {
    "id": "1766514823965",
    "name": "Recargador Solar",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422386/tierra-rog/recargador-solar_g6eldd.png",
    "factionCost": 4,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Provocar",
      "Sello",
      "Último suspiro"
    ]
  },
  {
    "id": "1766515266557",
    "name": "Argentinosaurio",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422359/tierra-rog/argentinosaurio_qamhzs.png",
    "factionCost": 3,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766515344353",
    "name": "El Último Titan",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422359/tierra-rog/el-ultimo-titan_tbcgrx.png",
    "factionCost": 4,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Lanzo"
    ]
  },
  {
    "id": "1766515476957",
    "name": "Mutación Clonada",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/mutacion-clonada_icoqlr.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Copio",
      "huevo",
      "Sobrecarga"
    ]
  },
  {
    "id": "1766515550677",
    "name": "¡Embosca-Huevos!",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422359/tierra-rog/embosca-huevos_ttiiee.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Daño",
      "huevo",
      "inflinjo"
    ]
  },
  {
    "id": "1766515609781",
    "name": "¡Sorpresa!",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422440/tierra-rog/sorpresa_jzfijw.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Cargar",
      "Criatura",
      "Eclosiono",
      "huevo"
    ]
  },
  {
    "id": "1766515655051",
    "name": "Una Nueva Era",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422442/tierra-rog/una-nueva-era_pftyy5.png",
    "factionCost": 4,
    "cost": 7,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Aniquilar",
      "curar"
    ]
  }, {
    "id": "1766512385849",
    "name": "Sello",
    "faction": "tierra",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422415/tierra-rog/sello_snxdfi.png",
    "factionCost": 0,
    "cost": 0,
    "banned": false,
    "isSeal": true,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": []
  },
  {
    "id": "1766512486637",
    "name": "Cría Hambienta",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422358/tierra-rog/cria-hambrienta_ou71oc.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al atacar"
    ]
  },
  {
    "id": "1766512559911",
    "name": "Evolución Temprana",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422360/tierra-rog/evolucion-temprana_wzkedu.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Coste",
      "Daño",
      "Reducir"
    ]
  },
  {
    "id": "1766512664491",
    "name": "Furia Jurásica",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422361/tierra-rog/furia-jurasica_nwmufr.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": true,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "aliada",
      "Ataque rápido",
      "Criatura",
      "otorgo"
    ]
  },
  {
    "id": "1766512711472",
    "name": "Microceraptor",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422384/tierra-rog/microceraptor_clpjgd.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766512862901",
    "name": "Madre Vigilante",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422383/tierra-rog/madre-vigilante_dy8cap.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766512922499",
    "name": "Pisotón",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/pisoton_z9qlkn.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": true,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Destruyo"
    ]
  },
  {
    "id": "1766512977483",
    "name": "Velocompi Robaoros",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422441/tierra-rog/velocompi_bc4gjb.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Carta",
      "Robar"
    ]
  },
  {
    "id": "1766513037215",
    "name": "Elegida de Tierra",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422360/tierra-rog/ELEGIDA-DE-TIERRA_umwnwg.png",
    "factionCost": 3,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Busco",
      "Criatura",
      "Mano",
      "Revelar"
    ]
  },
  {
    "id": "1766513080049",
    "name": "Turok, tanque Viviente",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422441/tierra-rog/turok_jqbnvl.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Aturdir",
      "Criatura"
    ]
  },
  {
    "id": "1766513127481",
    "name": "Xiara, Guardacostas",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422442/tierra-rog/xiara_aratyw.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "curar",
      "Daño"
    ]
  },
  {
    "id": "1766513200671",
    "name": "Zigzagón, El Trotamundos",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422444/tierra-rog/zigzagon_oj5iq5.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "Diagonal",
      "huevo",
      "Mover",
      "Último suspiro"
    ]
  },
  {
    "id": "1766513391795",
    "name": "Escalodón Solar",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422360/tierra-rog/escalodon_ei0me0.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Mazo",
      "Sello",
      "Último suspiro"
    ]
  },
  {
    "id": "1766513441789",
    "name": "Griska, El Cercenador",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422362/tierra-rog/griska_nmtesj.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Carta",
      "Robar"
    ]
  },
  {
    "id": "1766513506249",
    "name": "Khar, Apetito Insaciable",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422379/tierra-rog/khar_y2lokl.png",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Ataque rápido",
      "Aturdir",
      "Enfermedad",
      "Inmune"
    ]
  },
  {
    "id": "1766513552453",
    "name": "Necrorex",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422386/tierra-rog/necrorex_smtsoz.png",
    "factionCost": 2,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "Creo",
      "Destruyo",
      "huevo"
    ]
  },
  {
    "id": "1766513604829",
    "name": "Pyronodon",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/pyrodon_lqjzkw.png",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Daño",
      "inflinjo",
      "Oponente"
    ]
  },
  {
    "id": "1766513663741",
    "name": "Tiranía de Gigantes",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422441/tierra-rog/tirania-de-gigantes_dlg2ze.png",
    "factionCost": 3,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Destruyo"
    ]
  },
  {
    "id": "1766513706517",
    "name": "Titán Rompecielos",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422440/tierra-rog/titan-rompe-cielos_vgvnae.png",
    "factionCost": 3,
    "cost": 3,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766513814801",
    "name": "Yagor, Terror Prehistórico",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422443/tierra-rog/yagor_cjaaid.png",
    "factionCost": 4,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Al golpear",
      "Asalto",
      "Carta",
      "Criatura",
      "Gano",
      "Mazo",
      "Revelar"
    ]
  },
  {
    "id": "1766513878647",
    "name": "Zilagodon, Dios de la Tierra",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422444/tierra-rog/zilagodon_po1wl1.png",
    "factionCost": 5,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Criatura",
      "otorgo"
    ]
  },
  {
    "id": "1766513953557",
    "name": "Huevo Jurásico",
    "faction": "tierra",
    "rarity": "unlimited",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422361/tierra-rog/huevo-jurasico_lt40wl.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": true,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Criatura",
      "Revivo",
      "Token"
    ]
  },
  {
    "id": "1766514060469",
    "name": "Sembrador del Mañana",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422443/tierra-rog/zembrador-del-manana_gzigwt.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Coste"
    ]
  },
  {
    "id": "1766514260487",
    "name": "Vigila-Crías",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422442/tierra-rog/vigila-crias_vy0jil.png",
    "factionCost": 2,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Criatura",
      "Eclosiono",
      "otorgo"
    ]
  },
  {
    "id": "1766514560407",
    "name": "Bok Nubealta",
    "faction": "tierra",
    "rarity": "rare",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422358/tierra-rog/bok-nubealta_kqgpjs.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Caída libre"
    ]
  },
  {
    "id": "1766514604899",
    "name": "Impactador de Marea negra",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422362/tierra-rog/impactador-de-marea-negra_ouiypm.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Mover"
    ]
  },
  {
    "id": "1766514655547",
    "name": "Acarreador Enorme",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422357/tierra-rog/acarreador-enorrme_tqn32s.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Cargar",
      "Eclosiono"
    ]
  },
  {
    "id": "1766514741585",
    "name": "Mutante Tirano",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/mutante-tirano_gurehv.png",
    "factionCost": 4,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Asalto",
      "Copio",
      "Criatura"
    ]
  },
  {
    "id": "1766514823965",
    "name": "Recargador Solar",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422386/tierra-rog/recargador-solar_g6eldd.png",
    "factionCost": 4,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Provocar",
      "Sello",
      "Último suspiro"
    ]
  },
  {
    "id": "1766515266557",
    "name": "Argentinosaurio",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422359/tierra-rog/argentinosaurio_qamhzs.png",
    "factionCost": 3,
    "cost": 4,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Dejo",
      "huevo",
      "Último suspiro"
    ]
  },
  {
    "id": "1766515344353",
    "name": "El Último Titan",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422359/tierra-rog/el-ultimo-titan_tbcgrx.png",
    "factionCost": 4,
    "cost": 5,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Asalto",
      "Lanzo"
    ]
  },
  {
    "id": "1766515476957",
    "name": "Mutación Clonada",
    "faction": "tierra",
    "rarity": "common",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422385/tierra-rog/mutacion-clonada_icoqlr.png",
    "factionCost": 1,
    "cost": 0,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Alrededor",
      "Copio",
      "huevo",
      "Sobrecarga"
    ]
  },
  {
    "id": "1766515550677",
    "name": "¡Embosca-Huevos!",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422359/tierra-rog/embosca-huevos_ttiiee.png",
    "factionCost": 2,
    "cost": 1,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Daño",
      "huevo",
      "inflinjo"
    ]
  },
  {
    "id": "1766515609781",
    "name": "¡Sorpresa!",
    "faction": "tierra",
    "rarity": "epic",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422440/tierra-rog/sorpresa_jzfijw.png",
    "factionCost": 2,
    "cost": 2,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Cargar",
      "Criatura",
      "Eclosiono",
      "huevo"
    ]
  },
  {
    "id": "1766515655051",
    "name": "Una Nueva Era",
    "faction": "tierra",
    "rarity": "legendary",
    "img": "https://res.cloudinary.com/dzkxl45xy/image/upload/v1766422442/tierra-rog/una-nueva-era_pftyy5.png",
    "factionCost": 4,
    "cost": 7,
    "banned": false,
    "isSeal": false,
    "isToken": false,
    "isQuickSpell": false,
    "isSlowSpell": false,
    "isArtifact": false,
    "tags": [
      "Aniquilar",
      "curar"
    ]
  }
]
